version: '3'

services:
  jocko_a:
    build:
      context: .
    image: travisjeffery:jocko

  jocko_b:
    build:
      context: .
    image: travisjeffery:jocko
    command: jocko broker --serf-members=jocko_a:9094

  jocko_c:
    build:
      context: .
    image: travisjeffery:jocko
    command: jocko broker --serf-members=jocko_a:9094
